pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        
                
        stage('Checkout'){
           steps {
                git credentialsId: '0216668a-1ad3-4e4d-97e6-14eed63e2da2', 
                url: 'https://github.com/iam-veeramalla/cicd-end-to-end',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t sid716/jenkins_argocd_pipelines_sample:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u sid716 -p Siddu716$
                    docker push sid716/jenkins_argocd_pipelines_sample:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '0216668a-1ad3-4e4d-97e6-14eed63e2da2', 
                url: 'https://github.com/sid14581/Suppport_pipeline_argoCD_k8s.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '0216668a-1ad3-4e4d-97e6-14eed63e2da2', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        
                        sed -i "s@sid716.*@sid716/jenkins_argocd_pipelines_samples:${BUILD_NUMBER}@g" deploy.yaml
                        cat deploy.yaml

                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'

                        git remote -v
                        echo " "
                        git push https://github.com/sid14581/Suppport_pipeline_argoCD_k8s.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
