pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {
                        
        stage('Checkout'){
           steps {
                script {
                    git branch: 'main',
                        credentialsId: '018a1d01-02a7-4854-b556-c77635ada871',
                        url: 'https://github.com/sid14581/pipeline_project.git'
                }
           }           
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd  /var/jenkins_home/workspace/Pipeline_execution/python_argoCd_jenkins/
                    docker build -t sid716/jenkins_argocd_pipelines_sample:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u sid716 -p Siddu716$
                    docker push sid716/jenkins_argocd_pipelines_sample:${BUILD_NUMBER}
                    '''
                }
            }
        }

        // stage('Update K8S manifest & push to Repo'){
        //     steps {
        //         script{
        //             withCredentials([usernamePassword(credentialsId: '018a1d01-02a7-4854-b556-c77635ada871', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
        //                 sh '''

        //                 cd /var/jenkins_home/workspace/Pipeline_execution/deploy/

        //                 cat deploy.yaml
                        
        //                 sed -i "s@sid716.*@sid716/jenkins_argocd_pipelines_samples:${BUILD_NUMBER}@g" deploy.yaml
        //                 cat deploy.yaml

        //                 git add deploy.yaml
        //                 git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
        //                 echo " "
        //                 git remote -v
        //                 echo " "
                        
        //                 git push origin main
        //                 '''                        
        //             }
        //         }
        //     }
        // }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                script {
                    git branch: 'main',
                        credentialsId: '018a1d01-02a7-4854-b556-c77635ada871',
                        url: 'https://github.com/sid14581/Suppport_pipeline_argoCD_k8s.git'
                }
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '018a1d01-02a7-4854-b556-c77635ada871', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''

                        cd /var/jenkins_home/workspace/Pipeline_execution/deploy/

                        cat deploy.yaml
                        
                        sed -i "s@sid716.*@sid716/jenkins_argocd_pipelines_samples:${BUILD_NUMBER}@g" deploy.yaml
                        cat deploy.yaml

                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        echo " "
                        git remote -v
                        echo " "
                        
                        git push origin main
                        '''                        
                    }
                }
            }
        }
    }
}
